import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/LandingPage.module.css'
import Layout from '../components/Layout'
import Button from '../components/Button'
import { Col, Row } from 'react-bootstrap'
import { BsTelephone } from 'react-icons/bs'
import { FiLock } from 'react-icons/fi'
import { AiOutlineDownload } from 'react-icons/ai'
import CardLanding from '../components/CardLanding'

export default function Home() {
  const cardAbout = [
    {
      icon: BsTelephone,
      head: '24/7 Support',
      par: 'We have 24/7 contact support so you can contact us whenever you want and we will respond it.'
    },
    {
      icon: FiLock,
      head: 'Data Privacy',
      par: 'We make sure your data is safe in our database and we will encrypt any data you submitted to us.'
    },
    {
      icon: AiOutlineDownload,
      head: 'Easy Download',
      par: 'Zwallet is 100% totally free to use it’s now available on Google Play Store and App Store.'
    }
  ]

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main className='mt-5'>
          <header className='container'>
            <div className='row align-items-center'>
              <div className={`${styles.left} col-12 col-lg-6`}>
                <h1 className={`${styles.headText} fs-1`}>Awesome App <br/> For Saving <span className='text-primary'>Time.</span></h1>
                <p className='my-5 fs-4'>We bring you a mobile app for banking problems that oftenly wasting much of your times.</p>
                <Button grid>Try it free</Button>
              </div>
              <div className={`${styles.right} col-12 col-lg-6`}>
                <div className={`${styles.bgwave} d-inline-block position-absolute`}>
                  <Image width={1000} height={1000} quality={100} layout='intrinsic' src='/bg-wave.png' alt='wave' />
                </div>
                <div>
                  <Image layout='responsive' width={120} height={220} quality={100} src='/phone2.png' alt='phone' />
                </div>
              </div>
            </div>
          </header>

          <section className='bg-light py-5'>
            <div className='container'>
              <div className='text-center mt-5 mx-auto'>
                <h1 className={`${styles.headText} fs-1`}><span className='text-primary'>About</span> the Application.</h1>
                <p className='my-5 fs-4 w-75 mx-auto'>We have some great features from the application and it’s totally free to use by all users around the world.</p>
              </div>
              <Row>
                {cardAbout.map(item => {
                  return <CardLanding 
                    photo={<div className={`${styles.icon} bg-light`}>
                      <item.icon/>
                    </div>}
                    head={item.head}
                    par={item.par}
                    key={item.head}
                  />
                })}
              </Row>
            </div>
          </section>
        </main>
      </Layout>
    </div>
  )
}
