import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/LandingPage.module.css'
import Layout from '../components/Layout'
import Button from '../components/Button'
import { Col, Row } from 'react-bootstrap'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main className='mt-5'>
          <header className='container'>
            <div className='row align-items-center'>
              <div className={`${styles.left} col-12 col-lg-6`}>
                <h1 className={`${styles.headText} fs-1`}>Awesome App <br/> For Saving <span className='text-primary'>Time.</span></h1>
                <p className='my-5 fs-4'>We bring you a mobile app for banking problems that oftenly wasting much of your times.</p>
                <Button grid>Try it free</Button>
              </div>
              <div className={`${styles.right} col-12 col-lg-6`}>
                <div className={`${styles.bgwave} d-inline-block position-absolute`}>
                  <Image width={1000} height={1000} quality={100} layout='intrinsic' src='/bg-wave.png' alt='wave' />
                </div>
                <div>
                  <Image layout='responsive' width={120} height={220} quality={100} src='/phone2.png' alt='phone' />
                </div>
              </div>
            </div>
          </header>

          <section className='bg-light py-5'>
            <div className='container'>
              <div className='text-center mt-5 mx-auto'>
                <h1 className={`${styles.headText} fs-1`}><span className='text-primary'>About</span> the Application.</h1>
                <p className='my-5 fs-4 w-75 mx-auto'>We have some great features from the application and it’s totally free to use by all users around the world.</p>
              </div>
              <Row>
                <Col ms={12} lg={4}>
                  <div className='card'>

                  </div>
                </Col>
                <Col ms={12} lg={4}></Col>
                <Col ms={12} lg={4}></Col>
              </Row>
            </div>
          </section>
        </main>
      </Layout>
    </div>
  )
}
